baseURL = 'https://amatsuzero.github.io/LastStand/'
locale = 'zh-cn'
title = 'Last Stand'
theme = 'PaperMod'

[params]
ShowToc = true
TocOpen = true

[params.assets]
favicon = 'favicon.svg'
theme_color = '#111827'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[' , '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[markup.highlight]
guessSyntax = true

[taxonomies]
tag = 'tags'
category = 'categories'

[[menu.main]]
name = '标签'
url = '/tags/'
weight = 10

[[menu.main]]
name = '分类'
url = '/categories/'
weight = 20