baseURL = 'https://amatsuzero.github.io/LastStand/'
locale = 'zh-cn'
title = 'Last Stand'
theme = 'PaperMod'

[params]
ShowToc = true
TocOpen = true

[params.assets]
favicon = 'favicon.svg'
theme_color = '#111827'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/AmatsuZero/AmatsuZero'

[[params.socialIcons]]
name = 'email'
url = 'mailto:jzh16s@hotmail.com'

[[params.socialIcons]]
name = 'x'
url = 'https://x.com/DaubertJzh16s'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/jiangzhenhua/'

[[params.socialIcons]]
name = 'zhihu'
url = 'https://www.zhihu.com/people/jiang-zhen-hua-86'

[[params.socialIcons]]
name = 'telegram'
url = 'https://t.me/AMATSUZERO'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[' , '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[markup.highlight]
guessSyntax = true

[taxonomies]
tag = 'tags'
category = 'categories'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params.fuseOpts]
threshold = 0.3
distance = 100
ignorelocation = true
minmatchcharlength = 1
limit = 20
keys = ['title', 'permalink', 'summary']

[[menu.main]]
name = '标签'
url = '/tags/'
weight = 10

[[menu.main]]
name = '分类'
url = '/categories/'
weight = 20

[[menu.main]]
name = '关于我'
url = '/about/'
weight = 30

[[menu.main]]
name = '搜索'
url = '/search/'
weight = 40