#!/usr/bin/env python3
"""Export Hugo content into a safe, local Obsidian vault mirror.

The exporter intentionally has no third-party dependencies.  ``Library`` is a
generated, read-only view; hand-written notes and MOCs are never touched.
"""
from __future__ import annotations

import argparse, ast, hashlib, json, re, shutil, sys, tempfile, posixpath, os, datetime
from pathlib import Path
from urllib.parse import quote

MARKER = "<!-- Generated by scripts/obsidian-vault/export.py; DO NOT EDIT. -->"
DIR_MARKER = '.obsidian-export.json'
IMAGE_RE = re.compile(r'(?P<open>!?\[[^\]]*\]\(|!\s*)?(?P<path>(?:\./|\.\./|/)?[^\s)<>]+\.(?:png|jpe?g|gif|webp|svg|avif|mp4|webm|pdf))', re.I)
SHORTCODE_RE = re.compile(r'\{\{\s*<\s*(?P<name>/?[\w-]+)(?P<body>.*?)>\s*\}\}', re.S)

def scalar(value):
    value = value.strip()
    if not value: return None
    if value.startswith('{') and value.endswith('}'):
        result={}
        for item in value[1:-1].split(','):
            if '=' in item:
                key,val=item.split('=',1); result[key.strip().strip('"\'')]=scalar(val)
        return result
    if value.lower() in ('true','false'): return value.lower() == 'true'
    if value.lower() in ('null','nil'): return None
    try: return ast.literal_eval(value)
    except Exception:
        raw=value.strip('"\'')
        try: return datetime.datetime.fromisoformat(raw.replace('Z','+00:00'))
        except ValueError:
            try: return datetime.date.fromisoformat(raw)
            except ValueError: return raw

def parse_frontmatter(text):
    if text.startswith('+++'):
        end = text.find('\n+++', 3)
        if end < 0: return {}, text
        raw, body = text[4:end], text[end+4:]
        try:
            import tomllib
        except ImportError: tomllib=None
        try:
            if tomllib is None: raise ValueError('fallback parser')
            data = tomllib.loads(raw)
        except (ValueError, TypeError):
            data = {}
            for line in raw.splitlines():
                if '=' in line and not line.lstrip().startswith('#'):
                    k,v=line.split('=',1); data[k.strip()] = scalar(v)
        return data, body.lstrip('\n')
    if text.startswith('---'):
        end = text.find('\n---', 3)
        if end < 0: return {}, text
        data={}
        for line in text[4:end].splitlines():
            if ':' in line and not line.startswith((' ','-')):
                k,v=line.split(':',1); data[k.strip()] = scalar(v.split(' #',1)[0])
        return data, text[end+4:].lstrip('\n')
    return {}, text

def yaml_value(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int,float)): return str(v)
    if isinstance(v, (datetime.datetime,datetime.date,datetime.time)): return v.isoformat()
    if isinstance(v, dict): return '{' + ', '.join(json.dumps(str(k),ensure_ascii=False)+': '+yaml_value(x) for k,x in v.items()) + '}'
    if isinstance(v, list):
        return '[' + ', '.join(yaml_value(x) for x in v) + ']'
    return json.dumps(str(v), ensure_ascii=False)

def normalize_tag(tag):
    tag = str(tag).strip().replace(' ','-').replace('/','-')
    return re.sub(r'[^\w\-\u0080-\uffff]', '-', tag, flags=re.UNICODE).strip('-') or 'untagged'

def note_path(rel):
    p=Path(rel)
    if p.name == 'index.md': return p.parent.with_suffix('.md')
    if p.name == '_index.md': return p.parent / '_overview.md'
    return p

class Exporter:
    def __init__(self, source='content', vault='obsidian'):
        self.source=Path(source); self.vault=Path(vault); self.library=self.vault/'Library'
        self.mapping={}; self.docs=[]; self.warnings=[]; self.errors=[]; self.assets=[]; self.titles={}; self.anchors={}; self.relrefs=0; self.external_images=0; self.complex_html=0
    def discover(self):
        self.docs=sorted(self.source.rglob('*.md'))
        for p in self.docs:
            rel=p.relative_to(self.source).as_posix(); self.mapping[rel] = note_path(rel).as_posix()
            data,_=parse_frontmatter(p.read_text(encoding='utf-8', errors='replace'))
            if data.get('title'): self.titles[str(data['title']).strip().lower()] = rel
            _,body=parse_frontmatter(p.read_text(encoding='utf-8', errors='replace'))
            anchors={}
            for line in body.splitlines():
                m=re.match(r'^#{1,6}\s+(.+?)\s*\{#([-\w]+)\}\s*$',line)
                if m: anchors[m.group(2)] = re.sub(r'\s+#+$','',m.group(1)).strip()
            self.anchors[rel]=anchors
        return self.mapping
    def resolve(self, target, current):
        target=target.strip().strip('"\'')
        frag=''
        if '#' in target: target,frag=target.split('#',1)
        target=target.lstrip('/')
        if target.startswith('Library/'): target=target[8:]
        if target.startswith('posts/') and target[6:] in self.mapping: target=target[6:]
        base=Path(current).parent
        candidates=[]
        for raw in (base/target, Path(target)):
            raw=Path(posixpath.normpath(raw.as_posix()))
            candidates += [raw.as_posix(), (raw.with_suffix('.md')).as_posix(), (raw/'index.md').as_posix(), (raw/'_index.md').as_posix()]
            if raw.suffix == '.md': candidates += [(raw.with_suffix('')/'index.md').as_posix(), (raw.with_suffix('')/'_index.md').as_posix()]
        found=next((x for x in candidates if x in self.mapping), None)
        if not found and target.lower() in self.titles: found=self.titles[target.lower()]
        if not found:
            wanted=target.removeprefix('posts/')
            found=next((k for k,v in self.mapping.items() if v == wanted or v == target), None)
        if not found:
            # fallback by suffix (Hugo accepts paths rooted at content/posts)
            found=next((k for k in self.mapping if k.rstrip('.md').endswith(target.rstrip('.md'))), None)
        if not found and target.endswith('.md'):
            needle=target[:-3].rstrip('/')+'/index.md'
            matches=[k for k in self.mapping if k.endswith(needle)]
            if len(matches)==1: found=matches[0]
        if not found: self.warnings.append(f'unresolved relref: {target} ({current})'); return target + (('#'+frag) if frag else '')
        out='/Library/'+self.mapping[found]
        if frag in self.anchors.get(found,{}): frag=self.anchors[found][frag]
        return out + (('#'+frag) if frag else '')
    def transform(self, body, current):
        def sc(m):
            name, b=m.group('name').lower(), m.group('body').strip()
            if name in ('relref','ref'):
                self.relrefs += 1
                q=re.search(r'("[^"]+"|\'[^\']+\'|\S+)', b); path=self.resolve(q.group(0) if q else b,current)
                return path
            if name=='youtube':
                ident=b.split()[0].strip('"\'') if b else ''
                return f'[YouTube video](https://www.youtube.com/watch?v={ident})'
            if name=='details':
                sm=re.search(r'summary=["\']([^"\']+)',b); return '<details>\n<summary>'+((sm.group(1)) if sm else 'Details')+'</summary>\n'
            if name=='/details': return '</details>'
            self.warnings.append(f'unsupported shortcode: {name} ({current})'); return m.group(0)
        body=SHORTCODE_RE.sub(sc, body)
        self.external_images += len(re.findall(r'!\[[^\]]*\]\((?:https?:)?//',body,re.I))
        self.complex_html += len(re.findall(r'<(?:script|style|iframe|object|embed)\b|\s(?:style|class)=["\']',body,re.I))
        body=re.sub(r'\{#[-\w]+\}', '', body)
        # rewrite links to local markdown files and local assets relative to target note
        def link(m):
            pre,path=m.group(1),m.group(2)
            if path.startswith(('http://','https://','//','#','mailto:','/Library/')): return m.group(0)
            if path.lower().endswith('.md'):
                resolved=self.resolve(path,current)
                return pre+resolved
            src=(self.source/Path(current).parent/path).resolve()
            if src.exists() and src.is_file():
                resource_rel=src.relative_to(self.source.resolve()).as_posix()
                return pre+'/Library/'+resource_rel
            if pre.startswith('!'): self.errors.append(f'missing local asset: {path} ({current})')
            return m.group(0)
        body=re.sub(r'(!?\[[^\]]*\]\()([^\s)]+)', link, body)
        return body
    def render(self, rel, text):
        data,body=parse_frontmatter(text); tags=data.get('tags',[])
        if isinstance(tags,str): tags=[tags]
        data['source_tags']=tags; data['tags']=sorted({normalize_tag(x) for x in tags})
        data.update(source_path=rel, provenance='hugo-content', generated=True)
        title=data.get('title') or Path(rel).parent.name
        data.setdefault('aliases',[str(title)])
        head='---\n'+''.join(f'{k}: {yaml_value(v)}\n' for k,v in data.items())+'---\n\n'
        return head+self.transform(body,rel).rstrip()+'\n'
    def _owned_library(self):
        if not self.library.exists(): return True
        marker=self.library/DIR_MARKER
        if not marker.is_file(): return False
        try: data=json.loads(marker.read_text())
        except (OSError,json.JSONDecodeError): return False
        return data.get('generator')=='scripts/obsidian-vault/export.py' and data.get('version')==1
    def generate(self, write=True):
        self.discover(); outputs={}
        for p in self.docs:
            rel=p.relative_to(self.source).as_posix(); outputs[self.library/self.mapping[rel]]=MARKER+'\n'+self.render(rel,p.read_text(encoding='utf-8'))
        # copy non-markdown resources next to mapped notes, preserving source subdirectories
        for p in self.source.rglob('*'):
            if p.is_file() and p.name != '.DS_Store' and p.suffix.lower() not in ('.md',):
                rel=p.relative_to(self.source); outputs[self.library/rel]=p.read_bytes(); self.assets.append(rel.as_posix())
        manifest={'generator':'scripts/obsidian-vault/export.py','version':1,'articles':len(self.docs),'resources':len(self.assets),'mapping':self.mapping,
                  'files':{str(k.relative_to(self.library)):hashlib.sha256(v if isinstance(v,bytes) else v.encode()).hexdigest() for k,v in outputs.items()}}
        outputs[self.library/DIR_MARKER]=(json.dumps(manifest,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode()
        # Validate every generated local Markdown link against the complete
        # in-memory output set, so check does not depend on stale disk files.
        available={'/Library/'+p.relative_to(self.library).as_posix() for p in outputs}
        for path,data in outputs.items():
            if path.suffix!='.md': continue
            text=data if isinstance(data,str) else data.decode('utf-8')
            for target in re.findall(r'!?\[[^\]]*\]\((/Library/[^) #]+)',text):
                from urllib.parse import unquote
                if unquote(target) not in available: self.errors.append(f'broken generated link: {target} ({path})')
        if write:
            if not self._owned_library(): raise RuntimeError(f'refusing to replace unowned directory: {self.library}')
            tmp=Path(tempfile.mkdtemp(prefix='.obsidian-export-', dir=str(self.vault)))
            try:
                new=tmp/'Library'
                for dest in outputs:
                    q=new/dest.relative_to(self.library); q.parent.mkdir(parents=True,exist_ok=True); data=outputs[dest]; q.write_bytes(data if isinstance(data,bytes) else data.encode())
                backup=self.vault/'.Library.previous'
                if backup.exists(): shutil.rmtree(backup)
                if self.library.exists(): os.replace(self.library,backup)
                os.replace(new,self.library)
                if backup.exists(): shutil.rmtree(backup)
            finally: shutil.rmtree(tmp,ignore_errors=True)
        return outputs

    def check(self):
        outputs=self.generate(write=False)
        for path,data in outputs.items():
            expected=data if isinstance(data,bytes) else data.encode()
            if not path.is_file() or path.read_bytes()!=expected: self.errors.append(f'out of date: {path}')
        actual={p for p in self.library.rglob('*') if p.is_file()} if self.library.exists() else set()
        extra=actual-set(outputs)
        for p in sorted(extra): self.errors.append(f'unexpected generated file: {p}')
        return not self.errors

def main(argv=None):
    ap=argparse.ArgumentParser(); ap.add_argument('--source',default='content'); ap.add_argument('--vault',default='obsidian'); ap.add_argument('--check',action='store_true'); ap.add_argument('--report',action='store_true'); args=ap.parse_args(argv)
    e=Exporter(args.source,args.vault); ok=e.check() if args.check else True; outputs={} if args.check else e.generate(write=True)
    report={'articles':len(e.docs),'resources':len(e.assets),'relrefs':e.relrefs,'external_images':e.external_images,'complex_html':e.complex_html,'warnings':e.warnings,'errors':e.errors,'mapping':len(e.mapping)}
    if args.report or args.check: print(json.dumps(report,ensure_ascii=False,indent=2))
    # Warnings are deliberately reported for human review; conversion remains
    # usable for legacy Hugo references that cannot be resolved automatically.
    if args.check: return 0 if ok else 1
    return 0
if __name__=='__main__': sys.exit(main())
